### PR TITLE
change button style and positioning

### PR DESCRIPTION
**Pull request by Akshun-01**
## 👨‍💻 Changes proposed:
1) stylized the button from will width bar to a proper button
2) also stylized the end game button and repositioned it as well
3) made sure that all of this is responsive and working fine with the rest of the website

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2022

## 📷 Screenshots
Screenshot (231)
Screenshot (232)

### CODE REVIEW

**Comment by Akshun-01** [comment]
> Your work is awesome.✨
> 
> But the buttons are not visible on mobile view due to the footer.
> 
> image
> 
> I would suggest you place these buttons on top of the colored squares. 😊
> 
> image

Ok got it ... will work on it today 👍

**Comment by Akshun-01** [comment]
Hey @KiranAminPanjwani , I pushed the changes. please review them and provide feedback if scope for any more changes for this issue. 
thanks

**Comment by KiranAminPanjwani** [comment]
Dear, don't change the styling of the boxes. It has added too much spacing between the colored squares and it is not looking good.

image


Also, try to make your buttons responsive and position them in the center to improve the look of the website:

image

**Comment by Akshun-01** [comment]
Hi @KiranAminPanjwani , 
##Updates
I fixed that container bug (that happened due to incorrect closing divs : my bad)
I also added break points to improve its responsiveness, but its a bit jittery.(sry fr that)
Lastly, I tried centering it all like one below the other but in center , it does not look good. So, I changed it back to this but scaled it and added margin for it to look clean.

please review this, if u find any other bug or issue regarding this, please do tell.
thnx :)

**Comment by Akshun-01** [comment]
hey @KiranAminPanjwani , any updates on this one ?

**Comment by KiranAminPanjwani** [comment]
> hey @KiranAminPanjwani , any updates on this one ?

Dear, try to fix the issue properly, either try to locate the button in the center or try different stylings. Or else, close this PR and look for any other bug in the repository.

You can also visit my other repository:

**Pull request closed without merging**
