### PR TITLE
Added effects in the "win" and "lose" part

### PR DESCRIPTION
**Pull request by zugzwang03**
## 🛠️ Fixes Issue: #45 

I added typing effect in the "you win" and "you lose" section along with color variations.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2022

## 📷 Screenshots

https://user-images.githubusercontent.com/95460021/194233972-a0b34075-b410-45b1-88f2-7191b54bffc3.mp4

### CODE REVIEW

**Comment by zugzwang03** [comment]
Will I make it .5 s then?

**Comment by zugzwang03** [comment]
@KiranAminPanjwani

**Comment by zugzwang03** [comment]
@KiranAminPanjwani Will I make it .5 s then?

**Comment by KiranAminPanjwani** [comment]
> @KiranAminPanjwani Will I make it .5 s then?

Yes sure dear

**Pull request closed without merging**
