### PR TITLE
Added effects on the "you win" and "you lose" part

### PR DESCRIPTION
**Pull request by zugzwang03**
## 👨‍💻 Changes proposed:
I have added animation effects on the "you win" and "you lose" part.
the detail has been given on pull request #69 
Further that 0.5 s time delay has been set to make it appropriate with respect to time.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2022

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
> @KiranAminPanjwani

The animation is still very slow, the user won't wait to see the whole animation. Create animations in milliseconds to make the game more interesting for players.

**Comment by zugzwang03** [comment]
added to 100 milliseconds

**Comment by zugzwang03** [comment]
@KiranAminPanjwani

**Comment by zugzwang03** [comment]
@KiranAminPanjwani

**Pull request closed without merging**
