### PR TITLE
Added hover effect to squares

### PR DESCRIPTION
**Pull request by jackwebdev**
I added a hover effect. Sometimes you can get colours that are white or blend with the border. This makes it look kinda 3D looking. Screenshot below shows the effect in action. 😊

image

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
> I added a hover effect. Sometimes you can get colours that are white or blend with the border. This makes it look kinda 3D looking. Screenshot below shows the effect in action. 😊
> 
> image

That's Awesome! ✨
Please mention the issue number. Thank you.

**Comment by jackwebdev** [comment]
I never made an issue number, do you want me to make one?

**Comment by KiranAminPanjwani** [comment]
> I never made an issue number, do you want me to make one?

Yes. Kindly create an issue.
Also, I'm closing this PR. You have to create a new PR. Thank you.😊

**Comment by jackwebdev** [comment]
Ok thanks and will make an issue.

**Pull request closed without merging**
