### PR TITLE
Added effects to distinguish "win" and "lose" part

### PR DESCRIPTION
**Pull request by zugzwang03**
## 👨‍💻 Changes proposed:

I added some distinguished color changes in the win and lose part to keep it distinct, along with some box-shadow.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2022

## 📷 Screenshots

play
win
lose

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
Try adding some animation to the "You Lose" text, if possible. If the user loses the game a second time, the text should be slightly animated to make a difference.✨

**Comment by zugzwang03** [comment]
Can you explain a bit as to what kind of animations? like basic example or something

**Comment by zugzwang03** [comment]
anim
like this?

**Comment by KiranAminPanjwani** [comment]
> Can you explain a bit as to what kind of animations? like basic example or something

Something like these: 

https://d23mmnx9ld45h.cloudfront.net/misterhorse.com_web_v3/Products/Animation%20Composer/Main%20Page%20v2/Train%20Text%20Boxes/train_text_boxes_item_04.gif

https://i.stack.imgur.com/aKiOo.gif

https://codemyui.com/wp-content/uploads/2017/08/wave-text-animation.gif

These are just examples. You can add any kind of effect according to your convenience. You can search for some more examples, such as slide effect, appear effect, swipe effect, or type effect.

**Pull request closed without merging**
